const DEFAULT_FRAME_RATE = 60
const DEFAULT_FRAME_DELAY = 100
const DEFAULT_FRAME_COUNT = 60
const DEFAULT_PAGE_SCREENSHOT_DELAY = 100
const DEFAULT_MAX_CAPTURE_DURATION = 5000

module.exports = {
  DEFAULT_FRAME_RATE,
  DEFAULT_FRAME_DELAY,
  DEFAULT_PAGE_SCREENSHOT_DELAY,
  DEFAULT_MAX_CAPTURE_DURATION,
  DEFAULT_FRAME_COUNT
}
